logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 配置 useSSL=false 原因：较新版本的MySQL默认使用SSL协议连接，需要服务器证书验证才能连接成功
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lzumetal?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

grpc:
  server:
    port: 9091