user:
  username: 张三
  age: 22
  contactAddress[0]:
    province: hunan
    city: changsha
    area: yuhuaqu
  contactAddress[1]:
      province: guangdong
      city: guangzhou
      area: tianhequ

#激活哪一个环境的配置文件
spring:
 profiles:
  active: development
---
spring:
  profiles: development
db:
     url: jdbc:hsqldb:file:testdb
     username: dev
     password: dev
#在配置文件增加三个短横线区分不同的环境
---
spring:
     profiles: test
db:
     url: jdbc:mysql://192.168.128.5:3306/test
     username: root
     password: 123123
