// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.lzumetal.springboot.grpc.protocol;

/**
 * Protobuf type {@code BookListResponse}
 */
public final class BookListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BookListResponse)
    BookListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookListResponse.newBuilder() to construct.
  private BookListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookListResponse() {
    bookList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BookListResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lzumetal.springboot.grpc.protocol.BookServiceProto.internal_static_BookListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lzumetal.springboot.grpc.protocol.BookServiceProto.internal_static_BookListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lzumetal.springboot.grpc.protocol.BookListResponse.class, com.lzumetal.springboot.grpc.protocol.BookListResponse.Builder.class);
  }

  public static final int BOOKLIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.lzumetal.springboot.grpc.protocol.BookResponse> bookList_;
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.lzumetal.springboot.grpc.protocol.BookResponse> getBookListList() {
    return bookList_;
  }
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder> 
      getBookListOrBuilderList() {
    return bookList_;
  }
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  @java.lang.Override
  public int getBookListCount() {
    return bookList_.size();
  }
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  @java.lang.Override
  public com.lzumetal.springboot.grpc.protocol.BookResponse getBookList(int index) {
    return bookList_.get(index);
  }
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  @java.lang.Override
  public com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder getBookListOrBuilder(
      int index) {
    return bookList_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_ = 0;
  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bookList_.size(); i++) {
      output.writeMessage(1, bookList_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(2, total_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bookList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bookList_.get(i));
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, total_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lzumetal.springboot.grpc.protocol.BookListResponse)) {
      return super.equals(obj);
    }
    com.lzumetal.springboot.grpc.protocol.BookListResponse other = (com.lzumetal.springboot.grpc.protocol.BookListResponse) obj;

    if (!getBookListList()
        .equals(other.getBookListList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBookListCount() > 0) {
      hash = (37 * hash) + BOOKLIST_FIELD_NUMBER;
      hash = (53 * hash) + getBookListList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzumetal.springboot.grpc.protocol.BookListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lzumetal.springboot.grpc.protocol.BookListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BookListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BookListResponse)
      com.lzumetal.springboot.grpc.protocol.BookListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lzumetal.springboot.grpc.protocol.BookServiceProto.internal_static_BookListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lzumetal.springboot.grpc.protocol.BookServiceProto.internal_static_BookListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lzumetal.springboot.grpc.protocol.BookListResponse.class, com.lzumetal.springboot.grpc.protocol.BookListResponse.Builder.class);
    }

    // Construct using com.lzumetal.springboot.grpc.protocol.BookListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bookListBuilder_ == null) {
        bookList_ = java.util.Collections.emptyList();
      } else {
        bookList_ = null;
        bookListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lzumetal.springboot.grpc.protocol.BookServiceProto.internal_static_BookListResponse_descriptor;
    }

    @java.lang.Override
    public com.lzumetal.springboot.grpc.protocol.BookListResponse getDefaultInstanceForType() {
      return com.lzumetal.springboot.grpc.protocol.BookListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.lzumetal.springboot.grpc.protocol.BookListResponse build() {
      com.lzumetal.springboot.grpc.protocol.BookListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lzumetal.springboot.grpc.protocol.BookListResponse buildPartial() {
      com.lzumetal.springboot.grpc.protocol.BookListResponse result = new com.lzumetal.springboot.grpc.protocol.BookListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.lzumetal.springboot.grpc.protocol.BookListResponse result) {
      if (bookListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bookList_ = java.util.Collections.unmodifiableList(bookList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookList_ = bookList_;
      } else {
        result.bookList_ = bookListBuilder_.build();
      }
    }

    private void buildPartial0(com.lzumetal.springboot.grpc.protocol.BookListResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.total_ = total_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lzumetal.springboot.grpc.protocol.BookListResponse) {
        return mergeFrom((com.lzumetal.springboot.grpc.protocol.BookListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lzumetal.springboot.grpc.protocol.BookListResponse other) {
      if (other == com.lzumetal.springboot.grpc.protocol.BookListResponse.getDefaultInstance()) return this;
      if (bookListBuilder_ == null) {
        if (!other.bookList_.isEmpty()) {
          if (bookList_.isEmpty()) {
            bookList_ = other.bookList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBookListIsMutable();
            bookList_.addAll(other.bookList_);
          }
          onChanged();
        }
      } else {
        if (!other.bookList_.isEmpty()) {
          if (bookListBuilder_.isEmpty()) {
            bookListBuilder_.dispose();
            bookListBuilder_ = null;
            bookList_ = other.bookList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bookListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBookListFieldBuilder() : null;
          } else {
            bookListBuilder_.addAllMessages(other.bookList_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.lzumetal.springboot.grpc.protocol.BookResponse m =
                  input.readMessage(
                      com.lzumetal.springboot.grpc.protocol.BookResponse.parser(),
                      extensionRegistry);
              if (bookListBuilder_ == null) {
                ensureBookListIsMutable();
                bookList_.add(m);
              } else {
                bookListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.lzumetal.springboot.grpc.protocol.BookResponse> bookList_ =
      java.util.Collections.emptyList();
    private void ensureBookListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bookList_ = new java.util.ArrayList<com.lzumetal.springboot.grpc.protocol.BookResponse>(bookList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.lzumetal.springboot.grpc.protocol.BookResponse, com.lzumetal.springboot.grpc.protocol.BookResponse.Builder, com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder> bookListBuilder_;

    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public java.util.List<com.lzumetal.springboot.grpc.protocol.BookResponse> getBookListList() {
      if (bookListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookList_);
      } else {
        return bookListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public int getBookListCount() {
      if (bookListBuilder_ == null) {
        return bookList_.size();
      } else {
        return bookListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public com.lzumetal.springboot.grpc.protocol.BookResponse getBookList(int index) {
      if (bookListBuilder_ == null) {
        return bookList_.get(index);
      } else {
        return bookListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder setBookList(
        int index, com.lzumetal.springboot.grpc.protocol.BookResponse value) {
      if (bookListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookListIsMutable();
        bookList_.set(index, value);
        onChanged();
      } else {
        bookListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder setBookList(
        int index, com.lzumetal.springboot.grpc.protocol.BookResponse.Builder builderForValue) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder addBookList(com.lzumetal.springboot.grpc.protocol.BookResponse value) {
      if (bookListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookListIsMutable();
        bookList_.add(value);
        onChanged();
      } else {
        bookListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder addBookList(
        int index, com.lzumetal.springboot.grpc.protocol.BookResponse value) {
      if (bookListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookListIsMutable();
        bookList_.add(index, value);
        onChanged();
      } else {
        bookListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder addBookList(
        com.lzumetal.springboot.grpc.protocol.BookResponse.Builder builderForValue) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.add(builderForValue.build());
        onChanged();
      } else {
        bookListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder addBookList(
        int index, com.lzumetal.springboot.grpc.protocol.BookResponse.Builder builderForValue) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder addAllBookList(
        java.lang.Iterable<? extends com.lzumetal.springboot.grpc.protocol.BookResponse> values) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookList_);
        onChanged();
      } else {
        bookListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder clearBookList() {
      if (bookListBuilder_ == null) {
        bookList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public Builder removeBookList(int index) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.remove(index);
        onChanged();
      } else {
        bookListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public com.lzumetal.springboot.grpc.protocol.BookResponse.Builder getBookListBuilder(
        int index) {
      return getBookListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder getBookListOrBuilder(
        int index) {
      if (bookListBuilder_ == null) {
        return bookList_.get(index);  } else {
        return bookListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public java.util.List<? extends com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder> 
         getBookListOrBuilderList() {
      if (bookListBuilder_ != null) {
        return bookListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookList_);
      }
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public com.lzumetal.springboot.grpc.protocol.BookResponse.Builder addBookListBuilder() {
      return getBookListFieldBuilder().addBuilder(
          com.lzumetal.springboot.grpc.protocol.BookResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public com.lzumetal.springboot.grpc.protocol.BookResponse.Builder addBookListBuilder(
        int index) {
      return getBookListFieldBuilder().addBuilder(
          index, com.lzumetal.springboot.grpc.protocol.BookResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .BookResponse bookList = 1;</code>
     */
    public java.util.List<com.lzumetal.springboot.grpc.protocol.BookResponse.Builder> 
         getBookListBuilderList() {
      return getBookListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.lzumetal.springboot.grpc.protocol.BookResponse, com.lzumetal.springboot.grpc.protocol.BookResponse.Builder, com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder> 
        getBookListFieldBuilder() {
      if (bookListBuilder_ == null) {
        bookListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.lzumetal.springboot.grpc.protocol.BookResponse, com.lzumetal.springboot.grpc.protocol.BookResponse.Builder, com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder>(
                bookList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bookList_ = null;
      }
      return bookListBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 total = 2;</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 2;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {
      
      total_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      total_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BookListResponse)
  }

  // @@protoc_insertion_point(class_scope:BookListResponse)
  private static final com.lzumetal.springboot.grpc.protocol.BookListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lzumetal.springboot.grpc.protocol.BookListResponse();
  }

  public static com.lzumetal.springboot.grpc.protocol.BookListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookListResponse>
      PARSER = new com.google.protobuf.AbstractParser<BookListResponse>() {
    @java.lang.Override
    public BookListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BookListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lzumetal.springboot.grpc.protocol.BookListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

