// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.lzumetal.springboot.grpc.protocol;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string bookName = 2;</code>
   * @return The bookName.
   */
  java.lang.String getBookName();
  /**
   * <code>string bookName = 2;</code>
   * @return The bytes for bookName.
   */
  com.google.protobuf.ByteString
      getBookNameBytes();

  /**
   * <code>string author = 3;</code>
   * @return The author.
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 3;</code>
   * @return The bytes for author.
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string price = 4;</code>
   * @return The price.
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 4;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>.google.protobuf.Timestamp createTime = 5;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.google.protobuf.Timestamp createTime = 5;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <code>.google.protobuf.Timestamp createTime = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();
}
