// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.lzumetal.springboot.grpc.protocol;

public interface BookListByIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookListByIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 ids = 1;</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.Integer> getIdsList();
  /**
   * <code>repeated int32 ids = 1;</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <code>repeated int32 ids = 1;</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  int getIds(int index);
}
