// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.lzumetal.springboot.grpc.protocol;

public interface BookListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  java.util.List<com.lzumetal.springboot.grpc.protocol.BookResponse> 
      getBookListList();
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  com.lzumetal.springboot.grpc.protocol.BookResponse getBookList(int index);
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  int getBookListCount();
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  java.util.List<? extends com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder> 
      getBookListOrBuilderList();
  /**
   * <code>repeated .BookResponse bookList = 1;</code>
   */
  com.lzumetal.springboot.grpc.protocol.BookResponseOrBuilder getBookListOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  int getTotal();
}
