// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.lzumetal.springboot.grpc.protocol;

public final class BookServiceProto {
  private BookServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookAddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookAddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookGetByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookGetByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookListByIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookListByIdsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BookService.proto\032\033google/protobuf/emp" +
      "ty.proto\"/\n\016CommonResponse\022\014\n\004code\030\001 \001(\t" +
      "\022\017\n\007message\030\002 \001(\t\"<\n\014BookResponse\022\n\n\002id\030" +
      "\001 \001(\005\022\020\n\010bookName\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\"" +
      "B\n\020BookListResponse\022\037\n\010bookList\030\001 \003(\0132\r." +
      "BookResponse\022\r\n\005total\030\002 \001(\005\"2\n\016BookAddRe" +
      "quest\022\020\n\010bookName\030\001 \001(\t\022\016\n\006author\030\002 \001(\t\"" +
      " \n\022BookGetByIdRequest\022\n\n\002id\030\001 \001(\005\"#\n\024Boo" +
      "kListByIdsRequest\022\013\n\003ids\030\001 \003(\0052\330\001\n\013BookS" +
      "ervice\022/\n\007GetById\022\023.BookGetByIdRequest\032\r" +
      ".BookResponse\"\000\022)\n\003Add\022\017.BookAddRequest\032" +
      "\017.CommonResponse\"\000\0226\n\007listAll\022\026.google.p" +
      "rotobuf.Empty\032\021.BookListResponse\"\000\0225\n\tli" +
      "stByIds\022\025.BookListByIdsRequest\032\r.BookRes" +
      "ponse\"\0000\001B;\n%com.lzumetal.springboot.grp" +
      "c.protocolB\020BookServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookResponse_descriptor,
        new java.lang.String[] { "Id", "BookName", "Author", });
    internal_static_BookListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BookListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookListResponse_descriptor,
        new java.lang.String[] { "BookList", "Total", });
    internal_static_BookAddRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BookAddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookAddRequest_descriptor,
        new java.lang.String[] { "BookName", "Author", });
    internal_static_BookGetByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BookGetByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookGetByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_BookListByIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BookListByIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookListByIdsRequest_descriptor,
        new java.lang.String[] { "Ids", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
