// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.lzumetal.springboot.grpc.protocol;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
