server:
  port: 8090
  servlet:
    context-path: /cluster-session

spring:
  redis:
    host: 119.23.246.206
    port: 6379
    password: 123456
    database: 0
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        max-wait:
#  session:
#      store-type: redis