spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8090   #指定Admin-Server服务的http地址
server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息，而不是仅显示概要