server:
  servlet:
    context-path: /delayTask
  port: 8090
spring:
  redis:
    cluster:
      nodes:
        - 192.168.0.1:6379
        - 192.168.0.2:6379
        - 192.168.0.3:6379
      maxRedirects: 2
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 2s
    timeout: 15s
logging:
  config: classpath:logback.xml
